wip: compile errors fixed, still missing some symbols
```
Undefined symbols for architecture x86_64:
  "_omap3_dma4_init", referenced from:
      _omap3_mpu_init in omap3.o
  "_omap3_mmc_attach", referenced from:
      _beagle_common_init in beagle.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```